---
- ansible.builtin.include_tasks:
    file: pre.yml

- ansible.builtin.include_tasks:
    file: startup/manual.yml
  when: startup == "manual"

- ansible.builtin.include_tasks:
    file: startup/Systemd.yml
  when: startup == "systemd"

- name: OS specific
  include_tasks: os:/main.yml