---
- name: Install dev tools
  ansible.builtin.dnf:
    name:
      - nano
    state: latest
  become: true

- name: History
  ansible.builtin.lineinfile:
    path: /root/.bash_history
    regexp: '^{{ item }}'
    line: "{{ item }}"
  become: true
  loop:
  - "nano /etc/systemd/system/multi-user.target.wants/haproxy.service"
  - "cd {{ conf_dir }}"
  - "{{ app0_start }}"